/// Flutter icons OlhoLovepeople
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
// flutter:
//   fonts:
//    - family:  OlhoLovepeople
//      fonts:
//       - asset: fonts/OlhoLovepeople.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OlhoLovepeople {
  OlhoLovepeople._();

  static const _kFontFam = 'OlhoLovepeople';
  static const String? _kFontPkg = null;

  static const IconData olhinho_senha = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}